server: 
  port: 8080
  servlet:
      context-path: /
      
      

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

spring: 
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  mvc: 
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
 ### smtp mail 설정 추가 START (문재영_회원가입용)
  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp    
    default-encoding: UTF-8    
    username: tewaretest@gmail.com
    password: voewcofcrmhvuyhe
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2
### smtp mail 설정 추가 END (문재영_회원가입용)    
      
  #mariaDB 1 common
#  datasource-common: 
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy 
#    jdbc-url: jdbc:log4jdbc:mariadb://teraenergy.iptime.org:13306/teware?serverTimezone=UTC#no-log-set#spring.datasource-common.driver-class-name=org.mariadb.jdbc.Driver
#    username: teware
#    password: 2021
#    maximum-pool-size: 10
#    minimum-idle: 5
spring.datasource.hikari.common:
    driver-class-name: org.mariadb.jdbc.Driver
    platform: mariadb
    jdbc-url: jdbc:mariadb://teraenergy.iptime.org:13306/teware?serverTimezone=UTC&characterEncoding=UTF-8
    username: teware
    password: 2021
    maximum-pool-size: 10
    minimum-idle: 5